name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEBUG: "0"
      SECRET_KEY: "&duv3e64nxu3-(_#%$(h))oxfj)ax8(c0ltil!_q*$n_)lbmq9"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/cache@v2
      with:
        path: |
          /home/runner/.local/share/virtualenvs/
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pipenv
      run:  pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run Tests
      run: pipenv run test
