name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/cache@v2
      with:
        path: /home/runner/.local/share/virtualenvs/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pipenv
      run:  pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run Tests
      run: pipenv run test
